eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
    registry-fetch-interval-seconds: 5
server:
  port: 8082
spring:
  application:
    name: consumer
