eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
    registry-fetch-interval-seconds: 5
server:
  port: 8081
spring:
  application:
    name: producer
  datasource:
    #url: jdbc:postgresql://192.168.17.30:5432/test
    #username: gpadmin
    #password: gpadminPwd123!
    #driver-class-name: org.postgresql.Driver

    url: jdbc:mysql://192.168.43.87:3306/test?useUnicode=true&characterEncoding=gbk&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
